// libs/frontend-a/routes/home-page/src/lib/home-page.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'poc-nx-monorepo-home-page',
  templateUrl: './home-page.component.html',
  styleUrls: ['./home-page.component.scss']
})
export class HomePageComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="home-page row justify-content-center align-items-center">
  <div class="col-5">
    <div class="home-page__box p-5 d-flex flex-wrap">
      <h1 class="home-page__box--title">Aplicação Angular</h1>
      <p class="home-page__box--subtitle py-3">
        Este é um exemplo de aplicação <strong>angular</strong> em uma estrutura
        de Monorepo usando NX.
      </p>
      <div>
        <!-- Componente privado-->
        <p class="home-page__box--description">
          1. Este é um componente <strong>privado</strong> a projetos angular:
        </p>
        <frontend-a-private-button></frontend-a-private-button>
        <!-- Componente compartilhado -->
        <p class="home-page__box--description mt-4">
          2. Este é um componente <strong>compartilhado</strong> com os demais
          projetos do monorepo, agnóstico a framework
        </p>
        <shared-button></shared-button>
        <!-- <happynrwl-greeting title="aksdokasd"></happynrwl-greeting> -->
        <!-- Lib NPM Compartilhada -->
        <p class="home-page__box--description mt-4">
          3. Esta é uma lib NPM <strong>compartilhada</strong> com os demais
          projetos do monorepo
        </p>
      </div>
    </div>
  </div>
</div>

// libs/frontend-b/routes/home-page/src/lib/home-page.tsx
import './home-page.scss';
import { PrivateButtonComponent } from '../../../../components/private-button/src';

export function HomePage() {
  return (
    <div className="home-page row justify-content-center align-items-center">
      <div className="col-5">
        <div className="home-page__box p-5 d-flex flex-wrap">
          <h1 className="home-page__box--title">Aplicação React</h1>
          <p className="home-page__box--subtitle py-3">
            Este é um exemplo de aplicação <strong>react</strong> em uma
            estrutura de Monorepo usando NX.
          </p>
          <div>
            {/* Componente privado*/}
            <p className="home-page__box--description">
              1. Este é um componente react <strong>privado</strong> que pode
              ser utilizado apenas por este projeto:
            </p>
            <PrivateButtonComponent />
            {/* Componente compartilhado */}
            <p className="home-page__box--description mt-4">
              2. Este é um componente <strong>compartilhado</strong> com os
              demais projetos do monorepo, agnóstico a framework
            </p>
            <shared-button></shared-button>
            {/* Lib NPM Compartilhada */}
            <p className="home-page__box--description mt-4">
              3. Esta é uma lib NPM <strong>compartilhada</strong> com os demais
              projetos do monorepo
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default HomePage;
